Update streams.yaml
proxima-one/streams pull request #12
Opened 2023-05-17 15:24 UTC by alekseysavostin

2023-05-17 15:47 UTC, kalabukdima requested changes

2023-05-17 16:11 UTC, alekseysavostin commented on streams.yaml
>    description: "mangrove kandel smart contract events on polygon-mumbai"
Are you sure? These streams still in use

2023-05-18 13:39 UTC, kalabukdima commented on streams.yaml
>    description: "mangrove kandel smart contract events on polygon-mumbai"
Yes, it will just mark them with color in the UI so that the clients will not that you're not supposed to use those versions.

2023-05-19 08:32 UTC, kalabukdima approved these changes

2023-05-19 08:32 UTC, merged